
services:
  streamcompare-app:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - streamcompare-network

  # Optional: Add a reverse proxy for production
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - streamcompare-app
    networks:
      - streamcompare-network
    profiles:
      - production

networks:
  streamcompare-network:
    driver: bridge

volumes:
  nginx-certs: